/**
* This is an autogenerated file created by the Stencil compiler.
* It contains typing information for all components that exist in this project.
*/
/* tslint:disable */

import '@stencil/core';

import '@ionic/core';
import 'ionicons';
import '@stencil/redux';


export namespace Components {

  interface AppLogin {}
  interface AppLoginAttributes extends StencilHTMLAttributes {}

  interface AppRoom {
    'roomId': number;
  }
  interface AppRoomAttributes extends StencilHTMLAttributes {
    'roomId'?: number;
  }

  interface AppRooms {}
  interface AppRoomsAttributes extends StencilHTMLAttributes {}

  interface AppRoot {}
  interface AppRootAttributes extends StencilHTMLAttributes {}
}

declare global {
  interface StencilElementInterfaces {
    'AppLogin': Components.AppLogin;
    'AppRoom': Components.AppRoom;
    'AppRooms': Components.AppRooms;
    'AppRoot': Components.AppRoot;
  }

  interface StencilIntrinsicElements {
    'app-login': Components.AppLoginAttributes;
    'app-room': Components.AppRoomAttributes;
    'app-rooms': Components.AppRoomsAttributes;
    'app-root': Components.AppRootAttributes;
  }


  interface HTMLAppLoginElement extends Components.AppLogin, HTMLStencilElement {}
  var HTMLAppLoginElement: {
    prototype: HTMLAppLoginElement;
    new (): HTMLAppLoginElement;
  };

  interface HTMLAppRoomElement extends Components.AppRoom, HTMLStencilElement {}
  var HTMLAppRoomElement: {
    prototype: HTMLAppRoomElement;
    new (): HTMLAppRoomElement;
  };

  interface HTMLAppRoomsElement extends Components.AppRooms, HTMLStencilElement {}
  var HTMLAppRoomsElement: {
    prototype: HTMLAppRoomsElement;
    new (): HTMLAppRoomsElement;
  };

  interface HTMLAppRootElement extends Components.AppRoot, HTMLStencilElement {}
  var HTMLAppRootElement: {
    prototype: HTMLAppRootElement;
    new (): HTMLAppRootElement;
  };

  interface HTMLElementTagNameMap {
    'app-login': HTMLAppLoginElement
    'app-room': HTMLAppRoomElement
    'app-rooms': HTMLAppRoomsElement
    'app-root': HTMLAppRootElement
  }

  interface ElementTagNameMap {
    'app-login': HTMLAppLoginElement;
    'app-room': HTMLAppRoomElement;
    'app-rooms': HTMLAppRoomsElement;
    'app-root': HTMLAppRootElement;
  }


  export namespace JSX {
    export interface Element {}
    export interface IntrinsicElements extends StencilIntrinsicElements {
      [tagName: string]: any;
    }
  }
  export interface HTMLAttributes extends StencilHTMLAttributes {}

}
